__init__.py: error: Expression of type "tuple[str, stat_result | None]" is incompatible with return type "Tuple[str, stat_result]"
analysis_tasks.py: error: Argument of type "DataFrame | None" cannot be assigned to parameter "query_series" of type "DataFrame" in function "_get_filtered_dataset_and_query_feature"
analysis_tasks.py: error: Object of type "None" cannot be used as iterable value (reportOptionalIterable)
common.py: error: Cannot access attribute "__fields__" for class "type[ResponseMixin]*"
conftest.py: error: Argument of type "Literal['read']" cannot be assigned to parameter "access_type" of type "AccessType" in function "__init__"
data_validation.py: error: Argument of type "BinaryIO" cannot be assigned to parameter "filepath_or_buffer" of type "FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]" in function "read_csv"
data_validation.py: error: Cannot access attribute "all" for class "bool_t"
data_validation.py: error: Invalid conditional operand of type "Series | bool_t | Unknown"
data_validation.py: error: No overloads for "read_csv" match the provided arguments (reportCallIssue)
dataset.py: error: "value" is not a known attribute of "None" (reportOptionalMemberAccess)
dataset.py: error: Argument of type "list[dict[str, Series | Unknown | ndarray[Any, Unknown] | Any | NDArray[Unknown]]]" cannot be assigned to parameter "matching_properties" of type "List[Dict[str, str]]" in function "__init__" (reportArgumentType)
dataset_tasks.py: error: Expression of type "None" is incompatible with declared type "List[Unknown]"
download_tasks.py: error: Argument of type "ArrayLike" cannot be assigned to parameter "column_labels" of type "List[str] | None" in function "_handle_df_nas" (reportArgumentType)
env.py: error: Argument of type "str | PathLike[str] | None" cannot be assigned to parameter "fname" of type "StrOrBytesPath | IO[str] | RawConfigParser" in function "fileConfig" (reportArgumentType)
env.py: error: Object of type "None" is not subscriptable (reportOptionalSubscript)
factories.py: error: "Meta" overrides symbol of same name in class "Factory"
factories.py: error: Argument of type "BytesIO | BinaryIO | None" cannot be assigned to parameter "file" of type "BytesIO" in function "create_upload_file"
factories.py: error: Argument of type "IdMapping | None" cannot be assigned to parameter "id_mapping" of type "Json[IdMappingInsanity] | None" in function "add_feature_type" (reportArgumentType)
factories.py: error: Argument of type "Unknown | None" cannot be assigned to parameter "properties_to_index" of type "List[str]" in function "add_feature_type"
factories.py: error: Argument of type "Unknown | None" cannot be assigned to parameter "properties_to_index" of type "List[str]" in function "add_sample_type"
factories.py: error: Argument of type "_CallIfOmitted | Unknown" cannot be assigned to parameter "file" of type "BytesIO" in function "create_upload_file"
factories.py: error: Argument of type "_CallIfOmitted | Unknown" cannot be assigned to parameter "user" of type "str" in function "add_sample_type"
group.py: error: "group_entries" is not a known attribute of "None" (reportOptionalMemberAccess)
hdf5_utils.py: error: "Datatype" is not iterable
hdf5_utils.py: error: "__getitem__" method not defined on type "Datatype" (reportIndexIssue)
health_check.py: error: Cannot access attribute "delay" for class "function"
proxy.py: error: Argument of type "bytes" cannot be assigned to parameter "data" of type "RequestData | None" in function "post"
test_compute.py: error: Argument missing for parameter "self" (reportCallIssue)
types.py: error: Argument of type "Dict[str, AnnotationType] | None" cannot be assigned to parameter "annotation_type_mapping" of type "Dict[str, AnnotationType]" in function "validate_dimension_type_metadata"
types.py: error: Argument of type "Json[IdMappingInsanity] | None" cannot be assigned to parameter "id_mapping" of type "Dict[str, Any] | None" in function "__init__" (reportArgumentType)
types.py: error: Argument of type "Text" cannot be assigned to parameter "axis" of type "Literal['feature', 'sample']" in function "__init__"
types.py: error: Cannot assign to attribute "dataset_id" for class "DimensionType"
types.py: error: Expression of type "IdMapping" is incompatible with declared type "Json[IdMappingInsanity] | None"
types.py: error: Expression of type "None" cannot be assigned to parameter of type "Dict[str, AnnotationType]"
types.py: error: No overloads for "rename" match the provided arguments
utils.py: error: Cannot access attribute "detail" for class "Exception"
